name: Horilla TEMP Deploy

on:
  push:
    branches:
      - prod-temp
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TEMP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_TEMP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to TEMP EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_TEMP_HOST }} << 'EOF'
          set -e

          echo "🚀 TEMP deploy starting..."

          cd /home/ubuntu/horilla-hrm/horilla-hrm

          git reset --hard
          git clean -fd

          git fetch origin
          git checkout prod-temp
          git reset --hard origin/prod-temp

          fuser -k 8000/tcp || true

          source ../venv/bin/activate

          pip install -r requirements.txt


          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py compilemessages

          nohup python3 manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &

          echo "✅ TEMP deployment done"

          EOF
